# Generated by Django 5.0.6 on 2026-09-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image_url'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Specific products this promotion applies to (optional).', related_name='promotions', to='catalog.product'),
        ),
    ]
